//! Built-in language tables: aliases from `textmate-grammars-themes`, plus extensions
//! and file names for grammars whose JSON lacks `fileTypes`.

/// Alias to canonical grammar name.
pub const DEFAULT_ALIASES: &[(&str, &str)] = &[
    ("1c", "bsl"),
    ("1c-query", "sdbl"),
    ("adoc", "asciidoc"),
    ("ahk1", "ahk"),
    ("bash", "shellscript"),
    ("batch", "bat"),
    ("be", "berry"),
    ("bird", "bird2"),
    ("c#", "csharp"),
    ("c++", "cpp"),
    ("cdc", "cadence"),
    ("chpl", "chapel"),
    ("cjs", "javascript"),
    ("clj", "clojure"),
    ("closure-templates", "soy"),
    ("cmd", "vb"),
    ("coffeescript", "coffee"),
    ("console", "shellsession"),
    ("cql", "cypher"),
    ("cs", "csharp"),
    ("cts", "typescript"),
    ("dockerfile", "docker"),
    ("elisp", "emacs-lisp"),
    ("erl", "erlang"),
    ("f", "fortran-fixed-form"),
    ("f#", "fsharp"),
    ("f03", "fortran-free-form"),
    ("f08", "fortran-free-form"),
    ("f18", "fortran-free-form"),
    ("f77", "fortran-fixed-form"),
    ("f90", "fortran-free-form"),
    ("f95", "fortran-free-form"),
    ("for", "fortran-fixed-form"),
    ("fs", "fsharp"),
    ("fsl", "jssm"),
    ("ftl", "fluent"),
    ("gd", "gdscript"),
    ("gjs", "glimmer-js"),
    ("gql", "graphql"),
    ("gts", "glimmer-ts"),
    ("hbs", "handlebars"),
    ("hs", "haskell"),
    ("jade", "pug"),
    ("jl", "julia"),
    ("js", "javascript"),
    ("kql", "kusto"),
    ("kt", "kotlin"),
    ("kts", "kotlin"),
    ("lean4", "lean"),
    ("lisp", "common-lisp"),
    ("lit", "ts-tags"),
    ("makefile", "make"),
    ("mbt", "moonbit"),
    ("mbti", "moonbit"),
    ("md", "markdown"),
    ("mips", "mipsasm"),
    ("mjs", "javascript"),
    ("mmd", "mermaid"),
    ("mts", "typescript"),
    ("nar", "narrat"),
    ("nf", "nextflow"),
    ("nu", "nushell"),
    ("objc", "objective-c"),
    ("perl6", "raku"),
    ("pot", "po"),
    ("potx", "po"),
    ("properties", "ini"),
    ("protobuf", "proto"),
    ("ps", "powershell"),
    ("ps1", "powershell"),
    ("py", "python"),
    ("ql", "codeql"),
    ("rb", "ruby"),
    ("regex", "regexp"),
    ("rs", "rust"),
    ("scad", "openscad"),
    ("sh", "shellscript"),
    ("shader", "shaderlab"),
    ("shell", "shellscript"),
    ("spl", "splunk"),
    ("styl", "stylus"),
    ("surql", "surrealql"),
    ("talon", "talonscript"),
    ("tf", "terraform"),
    ("tfvars", "terraform"),
    ("tres", "gdresource"),
    ("ts", "typescript"),
    ("tscn", "gdresource"),
    ("tsp", "typespec"),
    ("typ", "typst"),
    ("vim", "viml"),
    ("vimscript", "viml"),
    ("vy", "vyper"),
    ("wl", "wolfram"),
    ("yml", "yaml"),
    ("zsh", "shellscript"),
];

/// File extension (without the dot) to grammar name; these override `fileTypes`.
pub const DEFAULT_EXTENSIONS: &[(&str, &str)] = &[
    ("go", "go"),
    ("py", "python"),
    ("pyi", "python"),
    ("pyw", "python"),
    ("js", "javascript"),
    ("mjs", "javascript"),
    ("cjs", "javascript"),
    ("ts", "typescript"),
    ("mts", "typescript"),
    ("cts", "typescript"),
    ("jsx", "jsx"),
    ("tsx", "tsx"),
    ("html", "html"),
    ("htm", "html"),
    ("css", "css"),
    ("scss", "scss"),
    ("json", "json"),
    ("jsonc", "jsonc"),
    ("rs", "rust"),
    ("c", "c"),
    ("h", "c"),
    ("cpp", "cpp"),
    ("cc", "cpp"),
    ("cxx", "cpp"),
    ("hpp", "cpp"),
    ("hxx", "cpp"),
    ("hh", "cpp"),
    ("cs", "csharp"),
    ("java", "java"),
    ("kt", "kotlin"),
    ("kts", "kotlin"),
    ("rb", "ruby"),
    ("php", "php"),
    ("lua", "lua"),
    ("sql", "sql"),
    ("md", "markdown"),
    ("xml", "xml"),
    ("xsl", "xml"),
    ("svg", "xml"),
    ("yaml", "yaml"),
    ("yml", "yaml"),
    ("toml", "toml"),
    ("sh", "shellscript"),
    ("bash", "shellscript"),
    ("zsh", "shellscript"),
    ("bat", "bat"),
    ("cmd", "bat"),
    ("ps1", "powershell"),
    ("psm1", "powershell"),
    ("psd1", "powershell"),
    ("swift", "swift"),
    ("vue", "vue"),
    ("svelte", "svelte"),
];

/// Exact file name (case-sensitive) to grammar name.
pub const DEFAULT_FILENAMES: &[(&str, &str)] = &[
    ("Makefile", "make"),
    ("makefile", "make"),
    ("GNUmakefile", "make"),
    ("Dockerfile", "docker"),
    ("Gemfile", "ruby"),
    ("Rakefile", "ruby"),
];

/// Language names that mean "no highlighting" and produce no diagnostic.
pub const PLAINTEXT_NAMES: &[&str] = &["text", "plaintext", "txt", "plain"];
