use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;

use serde::{Deserialize, Serialize};

/// One golden fixture generated by vscode-textmate: the source, and per theme the
/// expected token lines.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Fixture {
    #[serde(default)]
    pub vsctm_version: String,
    pub grammar: String,
    #[serde(default)]
    pub grammar_source_hash: String,
    /// Whether the generator honoured cross-grammar `injectTo` injections. Fixtures
    /// generated without them cannot match an engine that applies them.
    #[serde(default)]
    pub injections: bool,
    pub source: String,
    pub themes: BTreeMap<String, ThemeFixture>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ThemeFixture {
    pub tokens: Vec<Vec<FixtureToken>>,
    #[serde(default)]
    pub html: String,
}

/// A themed token as the generator writes it: UTF-8 byte offsets within the line,
/// scopes outermost first, the font style as vscode-textmate's bitmask.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FixtureToken {
    pub start: usize,
    pub end: usize,
    pub text: String,
    pub scopes: Vec<String>,
    #[serde(default)]
    pub color: String,
    #[serde(default)]
    pub font_style: u8,
}

pub fn load_fixture(path: &Path) -> io::Result<Fixture> {
    let bytes = fs::read(path)?;
    serde_json::from_slice(&bytes).map_err(|err| io::Error::new(io::ErrorKind::InvalidData, err))
}

/// Loads every `*.json` fixture in `dir`, sorted by file name.
pub fn load_fixtures(dir: &Path) -> io::Result<Vec<Fixture>> {
    let mut paths: Vec<_> = fs::read_dir(dir)?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    paths.sort();
    paths.iter().map(|path| load_fixture(path)).collect()
}
