name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: 1.93.0
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@49a0bdc70d2e1b713ca9e2869b211fcce03d3c1c # v2
      - run: cargo build --workspace --all-features
      - run: cargo test --workspace --all-features
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - run: cargo check -p kazari-rs --no-default-features
      - run: cargo test -p kazari-rs --no-default-features --features syntect,markdown --all-targets
      - run: cargo clippy -p kazari-rs --no-default-features --features syntect,markdown --all-targets -- -D warnings
      - run: cargo run -p kazari-rs --features markdown,syntect --example showcase -- --out target/showcase
      - run: cargo fmt --all --check
